#!/usr/bin/env bash

# https://launchpad.net/~aslatter/+archive/ubuntu/ppa
sudo add-apt-repository ppa:aslatter/ppa
sudo apt update

sudo apt install alacritty=0.15.1+1-20250526T050107\~jammy-b02e4fce
