#!/usr/bin/env bash

# https://github.com/tj/n

# need to run as the account user
su - "$SUDO_USER" -c "curl -fsSL https://raw.githubusercontent.com/mklement0/n-install/stable/bin/n-install | bash -s -- -y -n latest"
