#!/bin/bash

install_dotfiles() {
    echo 'Installing...'

    to=(
        ~/.gitconfig
        ~/.bash_profile
        ~/.bashrc
        ~/.zshrc
        ~/.vim
        ~/.vimrc
        ~/.gvimrc
        ~/.tmux.conf
        ~/.homestead/aliases
        ~/.tmuxinator
    )

    echo 'Deleting existing dotfiles'
    for file in ${to[@]}
    do
        rm -rf $file
    done

    from=(
        ~/.dotfiles/gitconfig
        ~/.dotfiles/bash_profile
        ~/.dotfiles/bashrc
        ~/.dotfiles/zshrc
        ~/.dotfiles/vim
        ~/.dotfiles/vim/vimrc
        ~/.dotfiles/vim/gvimrc
        ~/.dotfiles/tmux.conf
        ~/.dotfiles/aliases
        ~/.dotfiles/tmuxinator
    )

    echo 'Symlinking new dotfiles'
    for (( i = 0 ; i < ${#from[@]} ; i++ ))
    do
        ln -s ${from[$i]} ${to[$i]}
    done

    # eslintc doesn't like to be symlinked
    rm -rf ~/.eslintrc.json
    cp ~/.dotfiles/eslintrc.json ~/.eslintrc.json

    # copy the zsh theme
    cp ~/.dotfiles/custom.zsh-theme ~/.dotfiles/zsh/themes/custom.zsh-theme

    echo 'Finished!'
}


read -r -p "Are you sure you want to continue? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
    install_dotfiles
fi
