#!/bin/bash

NEOBUNDLE_DIR=~/.dotfiles/vim/bundle/neobundle.vim

TO=(
    ~/.gitconfig
    ~/.bash_profile
    ~/.bashrc
    ~/.zshrc
    ~/.vim
    ~/.vimrc
    ~/.gvimrc
    ~/.tmux.conf
    ~/.homestead/aliases
    ~/.tmuxinator
    ~/.dotfiles/zsh/custom/themes/walter.zsh-theme
    ~/.dotfiles/zsh/custom/themes/gitster.zsh-theme
)

FROM=(
    ~/.dotfiles/gitconfig
    ~/.dotfiles/bash_profile
    ~/.dotfiles/bashrc
    ~/.dotfiles/zshrc
    ~/.dotfiles/vim
    ~/.dotfiles/vim/vimrc
    ~/.dotfiles/vim/gvimrc
    ~/.dotfiles/tmux.conf
    ~/.dotfiles/aliases
    ~/.dotfiles/tmuxinator
    ~/.dotfiles/walter.zsh-theme
    ~/.dotfiles/gitster.zsh-theme
)


install_dotfiles() {
    echo 'Installing...'

    # echo 'Checking for NeoBundle'
    # if [ ! -d "$NEOBUNDLE_DIR" ]; then
    #     echo 'Installing NeoBundle'
    #     git clone https://github.com/Shougo/neobundle.vim $NEOBUNDLE_DIR
    # fi

    echo 'Deleting existing dotfiles'
    for file in ${TO[@]}
    do
        rm -rf $file
    done

    echo 'Symlinking new dotfiles'
    for (( i = 0 ; i < ${#FROM[@]} ; i++ ))
    do
        ln -s ${FROM[$i]} ${TO[$i]}
    done

    # eslintc doesn't like to be symlinked
    rm -rf ~/.eslintrc.json
    cp ~/.dotfiles/eslintrc.json ~/.eslintrc.json

    # copy the zsh theme
    # cp ~/.dotfiles/walter.zsh-theme ~/.dotfiles/zsh/custom/themes/walter.zsh-theme

    echo 'Finished!'
}


read -r -p "Are you sure you want to continue? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
    install_dotfiles
fi
