"     oooooo     oooo ooooo ooo        ooooo ooooooooo.     .oooooo
"      `888.     .8'  `888' `88.       .888' `888   `Y88.  d8P'  `Y8b
"       `888.   .8'    888   888b     d'888   888   .d88' 888
"        `888. .8'     888   8 Y88. .P  888   888ooo88P'  888
"         `888.8'      888   8  `888'   888   888`88b.    888
" .o.      `888'       888   8    Y     888   888  `88b.  `88b    ooo
" Y8P       `8'       o888o o8o        o888o o888o  o888o  `Y8bood8P'
"
" Author:     Walter Anderson <walteranderson19@gmail.com>
" Repository: https://bitbucket.org/walteranderson/dotfiles
"
" NeoBundle {{{

" Note: Skip initialization for vim-tiny or vim-small.
if 0 | endif
if has('vim_starting')
 if &compatible
   set nocompatible               " Be iMproved
 endif
 " Required:
 set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
" Required:
call neobundle#begin(expand('~/.vim/bundle/'))
" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'
" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!

NeoBundle 'kien/ctrlp.vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'bling/vim-airline'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'airblade/vim-gitgutter'
NeoBundle 'tomtom/tcomment_vim'
NeoBundle 'SirVer/ultisnips'
NeoBundle 'mattn/emmet-vim'
NeoBundle 'terryma/vim-multiple-cursors'
NeoBundle 'rking/ag.vim'
NeoBundle 'jreybert/vimagit'
NeoBundle 'gorodinskiy/vim-coloresque'
NeoBundle 'kristijanhusak/vim-hybrid-material'

NeoBundle 'L9' " required by fuzzy finder
NeoBundle 'FuzzyFinder'

NeoBundle 'junegunn/fzf', { 'dir': '~/.fzf' }
NeoBundle 'junegunn/fzf.vim'
NeoBundle 'wincent/terminus'

NeoBundle 'taglist.vim'
NeoBundle 'wdalmut/vim-phpunit'
NeoBundle 'roman/golden-ratio'
NeoBundle 'Yggdroot/indentLine'
NeoBundle 'Valloric/MatchTagAlways'

" autoclosing quotes/brackets/parens
" NeoBundle 'Raimondi/delimitMate'

" Language-specific plugins
NeoBundle 'fatih/vim-go'
NeoBundle 'digitaltoad/vim-jade'
NeoBundle 'groenewege/vim-less'
NeoBundle 'wavded/vim-stylus'
NeoBundle 'cakebaker/scss-syntax.vim'
NeoBundle 'StanAngeloff/php.vim'
NeoBundle 'xsbeats/vim-blade'
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'editorconfig/editorconfig-vim'
NeoBundle 'mustache/vim-mustache-handlebars'
NeoBundle 'posva/vim-vue'
NeoBundle 'othree/yajs.vim'

call neobundle#end()
" Required:
filetype plugin indent on
" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

" }}}
" Basic Options {{{

filetype plugin indent on
set nocompatible
set hidden
set expandtab
set encoding=utf-8
set nowrap
set visualbell
set ruler
set history=1000


" setting the length of a tab
  set tabstop=4 shiftwidth=4
" use mouse in terminal
  set mouse=a
" maintain context around cursor
  set scrolloff=10

" better copy and paste
  set pastetoggle=<F2>
  set clipboard=unnamed

" display incomplete commands
  set showcmd
" backspace through everything in insert mode
  set backspace=indent,eol,start
" Show partial commands on last line of window
  set showcmd
" automatically reload buffers when file changes
  set autoread

" Resize splits when the window is resized
  au VimResized * :wincmd =

 " more natural split opening
   set splitbelow
   set splitright

" force .md files to be markdown
  autocmd BufNewFile,BufReadPost *.md set filetype=markdown
  autocmd BufNewFile,BufReadPost *.md set wrap

" list characters
  set list
  set listchars=tab:»·,nbsp:·,trail:·,eol:¬,extends:❯,precedes:❮
  set showbreak=↪

" }}}
" Color Scheme & Display {{{

syntax on
set t_Co=256
set background=dark
colorscheme Tomorrow-Night-Eighties

" colorscheme hybrid_reverse
" let g:enable_bold_font = 1

" highlight VCS conflict markers
  match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'
" set title of terminal to the file
  set title
" or relativenumber
  set number
" add line markers at 80 characters and 120 characters
  set colorcolumn=80,120

" }}}
" Searching {{{

" highlight matches
set hlsearch
" incremental searching
set incsearch
" searches are case insensitive...
set ignorecase
" ... unless they contain at least one capital letter
set smartcase

" Keep search matches in the middle of the window.
nnoremap n nzzzv
nnoremap N Nzzzv

" }}}
" Backups {{{

set backup
set noswapfile

set undodir=~/.vim/tmp/undo//
set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//

" Make those folders automatically if they don't already exist.
if !isdirectory(expand(&undodir))
    call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
    call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
    call mkdir(expand(&directory), "p")
endif

" }}}
" Folding {{{

set foldlevelstart=0
set foldmethod=marker

" }}}
" Remapping {{{

" Leader key
  let mapleader = "\<Space>"

" escape to normal mode
  imap jk <esc>

" HJKL - quickly move through the document
  noremap H ^
  noremap L g_
  noremap J 5j
  noremap K 5k

" move through display lines
  nnoremap k gk
  nnoremap j gj

" remap ; to do :'s job
  noremap ; :

" easier movement between splits
  noremap <C-J> <C-W>j<CR>
  noremap <C-K> <C-W>k<CR>
  noremap <C-H> <C-W>h<CR>
  noremap <C-L> <C-W>l<CR>

" cycle between buffers
  noremap <leader>[ :bprevious<CR>
  noremap <leader>] :bnext<CR>

" close buffer
  map <leader>w :bd<CR>

" easy save
  map <leader>s :w<CR>

" disable vim insert mode completion
  inoremap <C-P> <nop>

" stay in visual mode when changing indentation
  vnoremap < <gv
  vnoremap > >gv

" pressing return clears higlighted search
  noremap <cr> :nohlsearch<cr>/<bs>

" auto change directory to match current file
nnoremap <leader>cd :cd %:p:h<CR>:pwd<CR>

" increase vertical split size
nmap <leader>v :vertical resize +10<CR>

" Laravel framework common files
nmap <leader>lr :e app/Http/routes.php<CR>
nmap <leader>lesp :e app/Providers/EventServiceProvider.php<CR>

nmap <leader>f :Ag 

" }}}
" Abbreviations {{{

abbrev art !php artisan
abbrev gm !php artisan make:model
abbrev gc !php artisan make:controller
abbrev gmig !php artisan make:migration

" }}}
" Plugin Settings {{{
" Tagbar {{{

"nnoremap <leader>r :TagbarToggle<CR>
let g:tagbar_singleclick=1
let g:tagbar_autoclose=1

" }}}
" Airline {{{

let g:airline#extensions#tabline#enabled = 0

" enable/disable status bar at the system level
set laststatus=2

let g:airline_theme='tomorrow'

if !exists('g:airline_symbols')
let g:airline_symbols = {}
endif

let g:airline_left_sep = ''
let g:airline_right_sep = ''

let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" }}}
" NerdTree {{{

map <leader>k :NERDTreeToggle<CR>:vertical resize 30<CR>
let g:NERDTreeShowHidden=1
let g:NERDTreeQuitOnOpen=1

" close nerdtree if it is the only window left open
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" }}}
" Syntastic {{{

map <leader>sc :SyntasticCheck<CR>

" using signs
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_enable_signs = 1
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"
let g:syntastic_style_error_symbol = "✗"

" using the quickfix window
let g:syntastic_enable_highlighting = 1
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0

" PHP checkers
let g:syntastic_php_checkers = ["php", "phpcs"]
let g:syntastic_php_phpcs_args = "--standard=PSR2 -n"

" Javascript checkers
let g:syntastic_javascript_checkers = ["eslint"]
let g:syntastic_eslint_args = "-c ~/.dotfiles/.eslint.json"

" do not check for errors on save
" let g:syntastic_mode_map = { "mode": "passive" }

let g:syntastic_html_tidy_ignore_errors=[" proprietary attribute " ,"trimming empty <", "unescaped &" , "lacks \"action", "is not recognized!", "discarding unexpected"]
let g:syntastic_check_on_wq = 0

let g:syntastic_quiet_messages = { "regex": 'camel caps format' }

" }}}
" editorconfig {{{

let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
let g:EditorConfig_exec_path = '/usr/local/bin/editorconfig'

" }}}
" Fugitive {{{

nnoremap <Leader>st :Gstatus<CR>
nnoremap <Leader>ci :Gcommit<CR>

" }}}
" Commentary {{{

autocmd FileType php setlocal commentstring=//\ %s

" }}}
" Utilsnips {{{

" path to snippets
let g:UltiSnipsSnippetDirectories=[$HOME.'/.dotfiles/snippets']

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"


" }}}
" Emmet {{{

let g:user_emmet_leader_key=','

" }}}
" EditorConfig {{{

let g:EditorConfig_exclude_patterns = ['fugitive://.*']

" }}}
" FuzzyFinder {{{

" nmap ,f :FufFileWithCurrentBufferDir<CR>
" nmap ,b :FufBuffer<CR>
nmap ,t :FufTaggedFile<CR>

nmap <leader>f :FufFileWithCurrentBufferDir<CR>
nmap <leader>b :FufBuffer<CR>

" }}}
" Taglist {{{

nmap <leader>t :TlistToggle<CR>

" }}}
" PHPUnit {{{

let g:phpunit_cmd = './vendor/bin/phpunit'

" }}}
" Golden Ratio {{{

let g:golden_ratio_exclude_nonmodifiable = 1

" }}}
" indentLine {{{

let g:indentLine_color_term = 239
let g:indentLine_char = '┆'

" }}}
" MatchTagAlways {{{

let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml' : 1,
    \ 'xml' : 1,
    \ 'jinja' : 1,
    \ 'blade' : 1,
    \}

" }}}
" fzf {{{

" This is the default extra key bindings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

" Default fzf layout
" - down / up / left / right
" - window (nvim only)
let g:fzf_layout = { 'down': '~40%' }

" For Commits and BCommits to customize the options used by 'git log':
let g:fzf_commits_log_options = '--graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr"'

" Advanced customization using autoload functions
autocmd VimEnter * command! Colors
  \ call fzf#vim#colors({'left': '15%', 'options': '--reverse --margin 30%,0'})

" }}}
" Multiple Cursors {{{

let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'

" }}}
" CtrlP {{{

" file/symbol searching
  noremap <leader>p :CtrlP<CR>
  noremap <leader>r :CtrlPBufTag<CR>

" search for filename in open buffers
  noremap <leader>j :CtrlPBuffer<CR>

" }}}
" Terminus {{{
let g:TerminusCursorShape=0
" }}}
