#!/usr/bin/env bash

echo 'Installing homebrew casks...'

casks=(
  'iterm2'
  'alfred'
  'bartender'
  'docker'
  # 'firefox'
  # 'google-chrome'
  # 'postman'
  # 'sequel-pro'
  # 'slack'
  'sublime-text'
  # '1password'
  'hammerspoon'
  # 'quicklook-json' # adds JSON preview support in finder's quicklook window
)

for cask in "${casks[@]}"
do
  echo " -- brew install --cask ${cask}"
  brew install --cask $cask
done
