#!/usr/bin/env bash

echo 'Installing homebrew packages...'

packages=(
  'vim'
  'tmux'
  'the_silver_searcher'
  'ripgrep'
)

for package in "${packages[@]}"
do
  echo " -- brew install ${package}"
  brew install $package
done
