#!/usr/bin/env bash

if ! type "brew" > /dev/null; then
  echo 'Installing Homebrew...'

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo 'Homebrew already installed'
fi

