#!/usr/bin/env bash

echo 'Installing homebrew casks...'

casks=(
  'iterm2'
  'alfred'
  'bartender'
  'docker'
  'firefox'
  'google-chrome'
  'postman'
  'sequel-pro'
  'slack'
  'sublime-text'
  '1password'
)

for cask in "${casks[@]}"
do
  echo " -- brew cask install ${cask}"
  brew cask install $cask
done
