#!/usr/bin/env bash

if ! type "brew" > /dev/null; then
  echo 'Installing Homebrew...'

  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo 'Installing packages/casks...'
  ./install-packages
else
  echo 'Homebrew already installed'
fi

